version: "2"

networks:
  app-network:


services:
  app:
    build:
      context: .
    image: 122610501872.dkr.ecr.us-west-2.amazonaws.com/pcap2:latest
    ports:
      - "8501:8501"
    networks:
      - app-network
